### ISSUE TITLE
Question: Is it version tvOS15 compatible?

### ISSUE THREAD

**Issue by bytedealer** [sebbo2002/pyatv-mqtt-bridge#99]
Hi @sebbo2002,

I used your app since a few months ago, everything okay since that. But now I recognized my AppleTV automatically updated to tvOS15 and it seems it does not work anymore. Do you think this is possible?

As long as I understodd pyatv was updated for this. Is it possible that you can have a look, too? Maybe you have to reimplement pyatv? I use your docker version.

Thanks a lot in advance!
bytedealer

**Comment by sebbo2002** [comment]
This is already on my todo list, but I haven't gotten around to it yet, I just haven't had the time. But I'm definitely on it.

Therefore, I recommend not updating to iOS 15 at this time if you rely on this module.

**Comment by bytedealer** [comment]
Hi @sebbo2002,

could load the new docker container and install it. I will do some tests later.

Thanks!
bytedealer

**Comment by bytedealer** [comment]
Hi @sebbo2002,

unfortunately I was not successful. I paired the AppleTV via Airplay but it seems that it gets no response.

Here the log:
bash-5.1$ atvremote --id F84537C4-08FE-4747-9396-F7269846361E --airplay-credentials xxx -v --debug command menu delay=10000                                               
2021-10-17 09:48:35 DEBUG: Binding on *:5353                                                                                
2021-10-17 09:48:35 DEBUG: Binding on 127.0.0.1:0                                                                           
2021-10-17 09:48:35 DEBUG: Binding on 169.254.117.207:0                                                                     
2021-10-17 09:48:35 DEBUG: Binding on 192.168.13.222:0                                                                      
2021-10-17 09:48:35 DEBUG: Binding on 172.17.0.1:0                                                                          
2021-10-17 09:48:35 DEBUG: Binding on 172.30.32.1:0                                                                         
2021-10-17 09:48:36 DEBUG: Auto-discovered Apple-TV-oben at 192.168.13.180:50574 (Protocol.MRP)                             
2021-10-17 09:48:36 DEBUG: Auto-discovered Apple-TV-oben at 192.168.13.180:7000 (Protocol.AirPlay)                          
2021-10-17 09:48:36 INFO: Auto-discovered Apple-TV-oben at 192.168.13.180                                                   
2021-10-17 09:48:36 DEBUG: Loaded AirPlay credentials: xxx
EB1BBD571204                                                                                                                
2021-10-17 09:48:36 DEBUG: Connection made to device                                                                        
2021-10-17 09:48:36 DEBUG: Configured keep-alive on <asyncio.TransportSocket fd=6, family=AddressFamily.AF_INET, type=Socket
Kind.SOCK_STREAM, proto=6, laddr=('192.168.13.222', 49868), raddr=('192.168.13.180', 50574)> (Linux)                        
2021-10-17 09:48:36 DEBUG: 192.168.13.222:49868<->192.168.13.180:50574  Connection established                              
2021-10-17 09:48:36 DEBUG: 192.168.13.222:49868<->192.168.13.180:50574 >> Send (Data=080f122434383739343431322d353635432d343
246432d423544382d4242383845393139393232432000a20183010a2432343238646536342d393863642d346634312d383564662d6134643563616433313
63036120570796174761a066950686f6e6522063138413339332a12636f6d2e6170706c652e545652656d6f746532063334342e32383801406c480150016
211636f6d2e6170706c652e54564d75736963680170017801880102a80101b00101)
2021-10-17 09:48:36 DEBUG: 192.168.13.222:49868<->192.168.13.180:50574 >> Send (Data=080f122434383739343431322d353635432d343
246432d423544382d4242383845393139393232432000a20183010a2432343238646536342d393863642d346634312d383564662d6134643563616433313
63036120570796174761a066950686f6e6522063138413339332a12636f6d2e6170706c652e545652656d6f746532063334342e32383801406c480150016
211636f6d2e6170706c652e54564d75736963680170017801880102a80101b00101)                                                        
2021-10-17 09:48:36 DEBUG: 192.168.13.222:49868<->192.168.13.180:50574 >> Send: Protobuf: type: DEVICE_INFO_MESSAGE         
identifier: "48794412-565D-42FC-B5D8-BB88E919922C"                                                                          
errorCode: NoError                                                                                                          
[deviceInfoMessage] {                                                                                                       
  uniqueIdentifier: "2428de64-98cd-4f41-85df-a4d5cad31606"                                                                  
  name: "pyatv"                                                                                                             
  localizedModelName: "iPhone"                                                                                              
  systemBuildVersion: "18A393"                                                                                              
  applicationBundleIdentifier: "com.apple.TVRemote"                                                                         
  applicationBundleVersion: "344.28"                                                                                        
  protocolVersion: 1                                                                                                        
  lastSupportedMessageType: 108                                                                                             
  supportsSystemPairing: true                                                                                               
  allowsPairing: true                                                                                                       
  systemMediaApplication: "com.apple.TVMusic"                                                                               
  supportsACL: true   
  supportsSharedQueue: true                                                                                                 
  supportsExtendedMotion: true                                                                                              
  sharedQueueVersion: 2                                                                                                     
  deviceClass: iPhone                                                                                                       
  logicalDeviceCount: 1                                                                                                     
}                                                                                                                           
Traceback (most recent call last):                                                                                          
  File "/usr/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 660, in _run_application                         
    return await cli_handler(loop)                                                                                          
  File "/usr/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 472, in cli_handler                              
    return await _handle_commands(args, config, loop)                                                                       
  File "/usr/lib/python3.8/site-packages/pyatv/scripts/atvremote.py", line 564, in _handle_commands                         
    atv = await connect(config, loop, protocol=args.protocol)                                                               
  File "/usr/lib/python3.8/site-packages/pyatv/__init__.py", line 76, in connect                                            
    await atv.connect()                                                                                                     
  File "/usr/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 703, in connect                                       
    await self._protocol.start()                                                                                            
  File "/usr/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 103, in start                                         
    self.device_info = await self.send_and_receive(msg)                                                                     
  File "/usr/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 180, in send_and_receive                              
    return await self._receive(identifier, timeout)                                                                         
  File "/usr/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 188, in _receive                                      
    await asyncio.wait_for(semaphore.acquire(), timeout)                                                                    
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for                                                         
    raise exceptions.TimeoutError()                                                                                         
asyncio.exceptions.TimeoutError                                                                                             
                                                                                                                            
>>> An error occurred, full stack trace above

But because it seems that has something to do with pyatv I wrote postlund.

I will update you here.

Bye
bytedealer

**Comment by bytedealer** [comment]
Hi @sebbo2002,

I found the error: With the new version it seems that you have to use the mac address as id in the config.json. If you use the other id ("AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE") you get the error "device not found".

Bye
bytedealer

**Comment by postlund** [comment]
You need to use one of the identifiers of the device. The one you used before was for MRP, which has been removed, so that is why your device isn't found. An easy way to find identifiers is with `atvremote scan`.
